// strings used in app

// HERO SECTION
export const HERO_SECTION = {
  APP_NAME: "Class-io",
  HERO_TEXT: "Revolutionize Attendance with Class-io",
  SUB_HERO_TEXT:
    "Secure, Effortless, and Accurate Attendance Taking and Tracking for Schools, Colleges, and Universities.",
  HERO_BUTTON_LABEL: "Follow Us",
};

// ABOUT AND FEATURE SECTION
export const ABOUT_AND_FEATURES = {
  WHAT_IS_CLASS_IO: "What is Class-io?",
  OVERVIEW_INTRO:
    "A brief overview of what Class-IO is, including its unique features.",
  CLASS_IO_DESCRIPTION:
    "Class-IO is a smart attendance management system designed to simplify and secure student attendance tracking using QR codes and geolocation. Say goodbye to outdated methods like paper sheets and manual sign-ins, and embrace a digital solution that prevents proxy attendance while ensuring data privacy.",
  ENHANCED_ACCURACY_SECURITY: {
    title: "Enhanced Accuracy & Security",
    description:
      "Geolocation ensures students are physically present in the classroom before checking in, preventing proxy attendance.",
  },
  EFFORTLESS_ATTENDANCE_MANAGEMENT: {
    title: "Effortless Attendance Management",
    description:
      "Scan QR codes to check in within seconds. Lecturers can generate attendance records with a single click.",
  },
  DATA_PRIVACY_FIRST: {
    title: "Data Privacy First",
    description:
      "All attendance data is encrypted and handled securely, prioritizing student privacy.",
  },
  SEAMLESS_INTEGRATION: {
    title: "Seamless Integration",
    description:
      "Built with Flutter, offering a smooth experience across both web and mobile platforms.",
  },
};

// HOW IT WORKS, DIFFERENTIATION AND USE CASE SECTION
export const HOW_IT_WORKS = {
  TITLE: "How It Works",
  DESCRIPTION: "See how Class-IO simplifies attendance in three simple steps.",
  STEP_1_LECTURER_ACTION: {
    title: "Create an Attendance Session",
    description:
      "Set up your session and generate a unique QR code with a unique token and your geolocation.",
  },
  STEP_1_STUDENT_ACTION: {
    title: "Check-In",
    description: "Confirm your presence using geolocation.",
  },
  STEP_2_LECTURER_ACTION: {
    title: "Monitor Attendance",
    description: "Track attendance in real-time as students check in.",
  },
  STEP_2_STUDENT_ACTION: {
    title: "Sign up for the Session",
    description: "Scan the QR code generated by the lecturer.",
  },
  STEP_3_LECTURER_ACTION: {
    title: "Export Reports",
    description: "Generate Excel reports for assessments and records.",
  },
  STEP_3_STUDENT_ACTION: {
    title: "Stay Updated",
    description: "View your attendance history from your student dashboard.",
  },
};

// WHY CHOOSE SECTION
export const WHY_CHOOSE = {
  TITLE: "Why Choose Class-IO?",
  GEOLOCATION_PROTECTION: {
    title: "Geolocation Protection",
    description:
      "No more proxy attendance—only students present in the classroom can check in.",
  },
  REAL_TIME_INSIGHTS: {
    title: "Real-Time Insights",
    description: "Monitor attendance live during each session.",
  },
  DATA_DRIVEN_DECISIONS: {
    title: "Data-Driven Decisions",
    description: "Export attendance data for easy grading and reporting.",
  },
  BUILT_WITH_FLUTTER: {
    title: "Built with Flutter",
    description: "Fast, responsive, and works across devices.",
  },
};

// USE CASES SECTION
export const USE_CASES = {
  TITLE: "Use Cases",
  UNIVERSITIES_COLLEGES: {
    title: "Universities & Colleges",
    description: "Simplify attendance for large classes and multiple sessions.",
  },
  SCHOOLS: {
    title: "Schools",
    description: "Encourage digital transformation in attendance management.",
  },
  INDIVIDUAL_LECTURERS: {
    title: "Individual Lecturers",
    description: "Manage smaller classes easily without paperwork.",
  },
};
